Fix for input and textarea bug
codex-team/editor.js pull request #1214
Opened 2020-06-22 14:52 UTC by PavlovicWorkCo

This PR should fix Issue #920 . 
A bit more detail about the issue:
Inputs and text areas are not handled properly.
In cases in which we want to have multiple text inputs in one custom plugin, some of them with formatable text and some of them without, we need to use inputs and/or text areas (for those which we don't want to have formatable text). In the current version this causes multiple bugs when hitting enter in inputs and textareas, because the `currentInput` is not updated properly and because the text in inputs and textareas is not innerHTML (it's in their value attribute).
Bugs:
1) It copy pastes the whole `<input>` element and puts it in the next paragraph outside of the block instead of only cutting out the text from the caret to the end. 
2) It cuts out the `<input>` element (without the text in it) and copies the whole content editable element.
![input-bugs](https://user-images.githubusercontent.com/47178050/85301257-e4d62900-b4a7-11ea-9d07-b21b2dd02274.gif)

2020-07-10 01:05 UTC, hata6502 commented
I support this PR!

2020-07-16 11:04 UTC, PavlovicWorkCo commented
@neSpecc @khaydarov @gohabereg Hi. Could you take a look at the issue and PR, and let me know if anything needs changing and if and when you would consider merging it. This bug is a blocker for a project that is soon going into production, so we would very much appreciate if it could be resolved without having to fork the repo. 🙏

2020-07-16 11:06 UTC, neSpecc commented
> @neSpecc @khaydarov @gohabereg Hi. Could you take a look at the issue and PR, and let me know if anything needs changing and if and when you would consider merging it. This bug is a blocker for a project that is soon going into production, so we would very much appreciate if it could be resolved without having to fork the repo. 🙏

we will check it soon. The next release is planned for the end of July.

2020-08-26 20:34 UTC, neSpecc requested changes

2020-08-26 20:34 UTC, neSpecc commented on src/components/utils.ts
> +export function isNativeTextInput(element: Node | HTMLElement): boolean {
we already have such util, see `dom.ts@isNativeInput`

2020-08-27 01:17 UTC, gohabereg approved these changes

2020-08-27 01:17 UTC, neSpecc approved these changes

2020-08-27 01:18 UTC, merged