Add RTL support
codex-team/editor.js pull request #1248
Opened 2020-07-25 01:07 UTC by ImangazalievM

Copied from https://github.com/codex-team/editor.js/pull/909

2020-07-26 14:10 UTC, talyguryn commented
Link for testing: https://deploy-preview-1248--editor-js.netlify.app/example-dev-rtl.html

2020-07-28 21:53 UTC, ImangazalievM commented
1.I fixed the positioning of icons in the toolbar.
2. Unfortunately, there is nothing I can do about text selection, this is the standard behavior when mixing RTL and LTR text

2020-08-24 13:06 UTC, talyguryn approved these changes

2020-08-26 17:10 UTC, ranemihir approved these changes

2020-08-26 17:15 UTC, neSpecc requested changes

2020-08-26 17:15 UTC, neSpecc commented on example/example-dev-rtl.html
> +    direction: 'rtl',
let's move this option to the `i18n` section, near `messages`

2020-08-26 17:17 UTC, neSpecc requested changes

2020-08-26 17:17 UTC, neSpecc commented on example/example-dev-rtl.html
> +<!--
let's name this file `example-rtl.html`

2020-08-26 17:22 UTC, neSpecc requested changes
There is an issue with arrow navigation between blocks. And there is no ability to move caret by arrows if it is at the start or at the end of the block.

For now, it checks the end of the block for `right` arrow and the start of the block for `left` arrow.

See blockEvents.ts `arrowRightAndDown` and `arrowLeftAndUp`

2020-08-26 22:08 UTC, neSpecc commented on src/components/__module.ts
> +  protected isRtl(): boolean {
maybe it would better to use getter instead of method?

2020-08-27 00:04 UTC, gohabereg commented on src/styles/rtl.css
> +.codex-editor.rtl-fix {
Why is it called `fix`? Maybe just add a modifier: `.codex-editor--rtl`

2020-08-27 00:04 UTC, neSpecc reviewed
Almost ready, but it still has some issues:

In the "narrow mode" (which enables when editor inserted in small containers) there are some issues. Try to remove underscore from the `ce-example__content--small` class at example-rtl.html.

The narrow mode is used in small containers, where is no place for the Plus button and for the Block Settings button. It have two features:
- the plus button is placed inside the editor column

<img width="739" alt="image" src="https://user-images.githubusercontent.com/3684889/91368495-f0303280-e811-11ea-95a3-1b8aef916330.png">

- additional padding-right added for the block settings button

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/3684889/91368480-e1e21680-e811-11ea-9496-c3b03042ad00.png">

We need to adopt these moments for the RTL

2020-08-27 15:37 UTC, neSpecc approved these changes

2020-08-27 15:43 UTC, gohabereg approved these changes

2020-08-27 15:51 UTC, talyguryn approved these changes

2020-08-27 15:52 UTC, merged

2020-09-23 14:31 UTC, javadbat commented
can we use it now?