Typos changes required to be fixed on website when using the import concept
codex-team/editor.js pull request #1260
Opened 2020-07-31 09:10 UTC by Gicehajunior

The misleading import concept typo on official documentation website need to be fixed. This may enhance no errors when importing modules.

2020-08-26 21:37 UTC, gohabereg requested changes

2020-08-26 21:37 UTC, gohabereg commented on README.md
> +import EditorJs from (@editorjs/editorjs);
```suggestion

```javascript
import EditorJS from '@editorjs/editorjs';
```

2020-08-27 01:22 UTC, gohabereg approved these changes

2020-08-27 01:23 UTC, neSpecc approved these changes

2020-08-27 01:23 UTC, merged