Add unique ids on next
codex-team/editor.js pull request #1333
Opened 2020-09-25 22:44 UTC by christoph-kluge

I'm adressing #873 with this PR.

Tested Features:

* Existing data: If your previous block does not have an "id" property, it will create a new unique id
* Existing data: If your previous block does have an "id" property, it will keep the existing unique id
* Existing data: If a block gets changed the "id" property stays the same
* Insert New Block: It will create a new unique id
* Move Blocks (Up/Down): It will keep the existing unique id

Important Note:
* If you "transform/transition" an existing block to another block it will receive a NEW unique id

2020-10-02 05:44 UTC, dsaralaya approved these changes

2020-10-19 18:34 UTC, sis-dk commented
Does this handle creating a new id when copying a block and pasting it as a new block? Initialise empty editor, type a para block, CMD+A (selects all the blocks. In our case the para block), CMD+V. Would the newly pasted block have a new id?

2020-10-19 19:12 UTC, christoph-kluge commented
@sis-dk thanks for spotting the copy & paste issue. I have adressed this in my latest commit

2020-10-31 02:09 UTC, mqtik commented
Why don't use shortid for id generation?
It's what I'm about to use in a module I'm working on (native side), but this one uses shortid to generate ID's.

Just want to keep consistent.

2020-10-31 11:24 UTC, christoph-kluge commented
I have used this feature on a custom build since 2.15.2 with UUIDs. Now I wanted to update for latest >2.18+ version and simply ported this feature with UUIDs. I think we could also add some custom configuration/callback to generate the IDs in a different way. Since One editor will not have quadrillions of entries I could imageine that shortids are pretty valid too 👍 

Maybe the maintainers (@neSpecc, @khaydarov, @gohabereg) could give a statement about this. I'm fine to add some custom configuration/callback to support custom-ids instead of hardcoded uuids.

2020-11-21 08:07 UTC, hata6502 requested changes

2020-11-21 08:07 UTC, hata6502 commented on src/components/modules/renderer.ts
> +    const id = item.id || _.generateUuidv4();
```suggestion
    const id = item.id;
```

When `const id` is undefined, a new ID is generated in `BlockManager.insert()`.

2020-12-16 10:50 UTC, ChasLui commented
I need this feature pls merge @christoph-kluge 🙏

2021-09-13 16:58 UTC, neSpecc commented
Resolved by #1667

2021-09-13 16:58 UTC, closed without merging