Fixes forr 2.19
codex-team/editor.js pull request #1356
Opened 2020-10-09 16:58 UTC by gohabereg

2020-10-09 18:03 UTC, neSpecc requested changes

2020-10-09 18:03 UTC, neSpecc commented on example/example.html
> +        @neSpecc neSpecc yesterday Author Member
༼ʘ̚ل͜ʘ̚༽

2020-10-09 18:03 UTC, neSpecc commented on types/api/blocks.d.ts
>     *
remove param from jsdoc

2020-10-09 18:11 UTC, khaydarov commented on example/example.html
> +        @gohabereg	Reply…
what is that

2020-10-12 16:07 UTC, neSpecc approved these changes

2020-10-12 18:12 UTC, khaydarov approved these changes

2020-10-12 21:03 UTC, merged