Fix SanitizerConfig type definition
codex-team/editor.js pull request #1456
Opened 2020-12-03 10:34 UTC by hata6502

2020-12-08 14:20 UTC, hata6502 commented on src/types-internal/html-janitor.d.ts
> +      [key: string]: Option | ((el: HTMLElement) => Option)
By adding `el: HTMLElement`, escape Type error with callback.

2021-01-26 17:16 UTC, neSpecc requested changes
PR description is not provided

2021-01-26 17:16 UTC, neSpecc commented on docs/CHANGELOG.md
> +- `Fix` - Fix SanitizerConfig type definition[#1456](https://github.com/codex-team/editor.js/pull/1456)
pls, move this line to the 2.19.2 section 
```suggestion
- `Fix` - Fix SanitizerConfig type definition [#1456](https://github.com/codex-team/editor.js/pull/1456)
```

2021-01-26 17:16 UTC, neSpecc commented on src/types-internal/html-janitor.d.ts
> +  type Option = boolean | { [attr: string]: boolean | string };
docs missed

2021-01-26 17:16 UTC, neSpecc commented on types/configs/sanitizer-config.d.ts
> +type Option = boolean | { [attr: string]: boolean | string };
docs are missed

2021-01-26 20:05 UTC, hata6502 commented
@neSpecc 

Sorry, I sent a issue. 
https://github.com/codex-team/editor.js/issues/1513

I feel great to install Contribution Inspector!
https://github.com/codex-team/editor.js/pull/1512

2021-01-31 14:40 UTC, hata6502 commented
@neSpecc
Would you review or edit this PR?

2021-02-04 12:35 UTC, khaydarov approved these changes

2021-02-18 17:58 UTC, neSpecc commented
Please pull the `next` branch

2021-02-18 18:17 UTC, khaydarov commented
@neSpecc I did

2021-02-19 14:34 UTC, hata6502 commented on src/components/modules/blockManager.ts
> +   * @returns {Block | undefined} can return undefined in case when the passed child note is not a part of the current editor instance
Fixed  for `yarn lint:fix`

2021-02-19 14:36 UTC, hata6502 commented
Resolved conflicts.

2021-02-27 21:23 UTC, gohabereg approved these changes

2021-03-02 13:32 UTC, neSpecc approved these changes

2021-03-02 13:34 UTC, merged