codemirror support added
codex-team/editor.js pull request #1473
Opened 2020-12-11 23:03 UTC by robonetphy

resolve #1433

2020-12-12 08:19 UTC, neSpecc reviewed
This feature is not related to CodeMirror. It just a helpful thing, that can be used for many tools.

2020-12-12 08:19 UTC, neSpecc commented on types/tools/block-tool.d.ts
> +  isPreventDefaultSupported?: boolean;
preventDefaultEvents

2020-12-12 08:19 UTC, neSpecc commented on types/tools/block-tool.d.ts
> +  * Is Tool prevent default event of editor.js, this property should return true
the description is not clear

2020-12-12 08:19 UTC, neSpecc commented on src/components/modules/blockEvents.ts
> +    if (this.Editor.Tools.isPreventDefaultSupported(tool)) {
it's better to access it via the  `INTERNAL_SETTINGS` map. It will help us to rename such settings in the future

2020-12-22 16:55 UTC, neSpecc commented on src/components/modules/tools.ts
> +   * Returns true if tool Is Tool handles the default event explicitly
```suggestion
   * Returns true if the Tool decide to handle key downs manually
```

2020-12-22 16:55 UTC, neSpecc commented on src/components/modules/tools.ts
> +  public preventDefaultEvents(tool: BlockToolConstructable): boolean {
```suggestion
  public isDefaultEventsPrevented(tool: BlockToolConstructable): boolean {
```

2020-12-22 16:55 UTC, neSpecc commented on src/components/modules/tools.ts
> +  public preventDefaultEvents(tool: BlockToolConstructable): boolean {
where do you use this method?

2021-01-26 17:10 UTC, neSpecc requested changes

2021-01-26 17:10 UTC, neSpecc commented on example/example-codemirror.html
> +<!DOCTYPE html>
remove this page before merge

2021-01-26 17:10 UTC, neSpecc commented on types/tools/block-tool.d.ts
> +  * Is Tool handles the default event explicitly,this property should return true
Please provide a more easy-understandable description of the use case of this option.

2021-02-03 11:25 UTC, hata6502 requested changes
Please write `docs/CHANGELOG.md`.

2021-02-03 15:08 UTC, hata6502 commented
@neSpecc 
I think the following issue should be resolved first of all. 
https://github.com/codex-team/editor.js/issues/1386

2021-03-16 16:45 UTC, neSpecc commented
This feature is not required since we fixed the original issue https://github.com/codex-team/editor.js/pull/1563

Thanks @robonetphy @hata6502 @khaydarov

2021-03-16 16:45 UTC, closed without merging