Feature: remove bundles
codex-team/editor.js pull request #1541
Opened 2021-02-17 15:31 UTC by talyguryn

Remove bundles for easy merging.

2021-02-17 15:34 UTC, gohabereg approved these changes

2021-02-17 16:12 UTC, neSpecc requested changes
Can not be merged without budling github actions

2021-02-17 17:03 UTC, neSpecc requested changes

2021-02-17 17:03 UTC, neSpecc commented on example/example-rtl.html
>      <div id="hint" style="text-align: center;">
```suggestion
    <div id="hint-tools" style="text-align: center;">
```

2021-02-17 17:03 UTC, neSpecc commented on example/example-i18n.html
> +<script src="../dist/editor.js" onload="document.getElementById('hint-core').hidden = true"></script>
where is the `hint-core` on this page?

2021-02-17 17:08 UTC, talyguryn commented on example/example-rtl.html
>      <div id="hint" style="text-align: center;">
thanks

2021-02-17 17:08 UTC, talyguryn commented on example/example-i18n.html
> +<script src="../dist/editor.js" onload="document.getElementById('hint-core').hidden = true"></script>
sorry. missed

2021-02-17 17:29 UTC, neSpecc approved these changes

2021-02-18 07:36 UTC, neSpecc approved these changes

2021-02-18 11:06 UTC, merged