refactoring(modules): Tooltip module is util now
codex-team/editor.js pull request #1601
Opened 2021-03-16 19:23 UTC by robonetphy

2021-03-16 19:25 UTC, neSpecc requested changes

2021-03-16 19:25 UTC, neSpecc commented on src/components/utils/tooltip.ts
> +export default new Tooltip();
its better to create an instance in a class constructor or in the method where it used, rather than use a singletone

2021-03-16 19:25 UTC, neSpecc commented on src/components/modules/api/tooltip.ts
> +import ITooltip from '../../utils/tooltip';
`I` means `Interface`, so it should be used near type, not util itself

2021-03-31 17:49 UTC, neSpecc approved these changes

2021-04-06 08:07 UTC, gohabereg approved these changes

2021-04-07 17:55 UTC, neSpecc commented on src/components/modules/toolbar/inline.ts
> +      Tools,
why did it change?

2021-04-08 16:47 UTC, merged