[Dev] Tools utils tests
codex-team/editor.js pull request #1602
Opened 2021-03-17 04:59 UTC by gohabereg

2021-03-22 12:50 UTC, neSpecc requested changes

2021-03-22 12:50 UTC, neSpecc commented on test/cypress/tests/modules/Tools.spec.ts
> +  function constructModule(config: EditorConfig = defaultConfig): Tools {
add a jsdoc please

2021-03-22 12:50 UTC, neSpecc commented on test/cypress/tests/modules/Tools.spec.ts
> +    module.state = {
what is the module's `state`?

2021-03-22 12:50 UTC, neSpecc commented on src/components/modules/tools.ts
> +        isInternal: true,
is it necessary to add this excess param to every item? they are all internal

2021-03-22 12:50 UTC, neSpecc commented on test/cypress/plugins/index.ts
> +  options.typescript = require.resolve('typescript');
please add a description of what is going on here

2021-03-22 12:50 UTC, neSpecc commented on test/cypress/tests/modules/Tools.spec.ts
> +          } as any,
does the prepare() with error missed? why it is unavailable

2021-03-22 12:50 UTC, neSpecc commented on test/cypress/tests/tools/BlockTool.spec.ts
> +  const options = {
describe this constant, please. What kind of options?

2021-03-22 12:50 UTC, neSpecc commented on test/cypress/tests/tools/BlockTool.spec.ts
> +    config: {
why it still named `config`? I would suggest `settings`

2021-03-22 12:50 UTC, neSpecc commented on test/cypress/tests/tools/BlockTool.spec.ts
> +      expect(tool.settings).to.be.deep.eq(options.config.config);
settings or config? It's confusing

2021-03-22 12:50 UTC, neSpecc commented on test/cypress/tests/tools/BlockTool.spec.ts
> +    it('should not fail if Tool prepare method is not exist', () => {
```suggestion
    it('should not fail if Tool reset method is not exist', () => {
```

2021-03-22 12:50 UTC, neSpecc commented on test/cypress/tests/tools/BlockTune.spec.ts
> +  const options = {
describe please

2021-03-22 12:50 UTC, neSpecc commented on test/cypress/tests/tools/BlockTune.spec.ts
> +      config: {
`config.config` again

2021-03-22 12:50 UTC, neSpecc commented on test/cypress/tests/tools/BlockTune.spec.ts
> +    it('should not fail if Tool prepare method is not exist', () => {
```suggestion
    it('should not fail if Tool reset method is not exist', () => {
```

2021-03-22 12:50 UTC, neSpecc commented on test/cypress/tests/tools/InlineTool.spec.ts
> +  const options = {
describe pls

2021-03-22 12:50 UTC, neSpecc commented on test/cypress/tests/tools/InlineTool.spec.ts
> +    it('should not fail if Tool prepare method is not exist', () => {
```suggestion
    it('should not fail if Tool reset method is not exist', () => {
```

2021-03-22 12:54 UTC, neSpecc commented on test/cypress/tests/tools/ToolsCollection.spec.ts
> +  const fakeTools = [
what is this? Need a description

2021-03-22 12:54 UTC, neSpecc commented on test/cypress/tests/tools/ToolsCollection.spec.ts
> +
Describe what should be tested here.

2021-03-27 19:20 UTC, gohabereg commented on src/components/modules/tools.ts
> +        isInternal: true,
To know if Tool is internal on the later stage we need to add it here

2021-03-27 19:22 UTC, gohabereg commented on test/cypress/tests/modules/Tools.spec.ts
> +          } as any,
It doesn't have required methods: save, surround, checkState

2021-03-27 19:24 UTC, gohabereg commented on test/cypress/tests/tools/BlockTool.spec.ts
> +      expect(tool.settings).to.be.deep.eq(options.config.config);
It was the same before. I'd suggest to discuss and change it separately

2021-03-29 09:46 UTC, neSpecc approved these changes

2021-03-30 17:09 UTC, khaydarov approved these changes

2021-04-04 08:38 UTC, merged