refactoring: notifier is util now
codex-team/editor.js pull request #1628
Opened 2021-04-05 17:58 UTC by talyguryn

2021-04-05 18:05 UTC, neSpecc requested changes
No description provided.

2021-04-06 08:07 UTC, gohabereg approved these changes

2021-04-06 18:06 UTC, neSpecc requested changes
And what about usages?

2021-04-06 18:06 UTC, neSpecc commented on src/types-internal/editor-modules.d.ts
> +import Notifier from '../components/utils/notifier';
it is not a module anymore, so it should not be here

2021-04-14 20:19 UTC, neSpecc approved these changes

2021-04-14 20:19 UTC, neSpecc commented on docs/CHANGELOG.md
> +- `Refactoring` - Notifier module now is a util.
wrong section

2021-04-15 17:20 UTC, merged