Fixed sanitizer on pasting HTML
codex-team/editor.js pull request #1686
Opened 2021-05-20 09:38 UTC by woren951

When I paste HTML text, sanitizer remove all inline tags and render only inner text. Because to HTMLJanitor passing wrong config.

2021-09-15 17:39 UTC, alxndr commented
Any ETA for this fix?

2021-10-20 17:29 UTC, pawelbajgrowicz commented
@neSpecc @khaydarov @gohabereg are you planning to check this pull request in the near future? This would be really great :rocket:

2021-10-25 12:40 UTC, Broutard commented
Any news on it ? The bug appeared since 2.20.0

2022-01-17 15:01 UTC, swapster commented
@gohabereg @khaydarov @neSpecc, Hi! Could you please check this PR?

2022-02-10 20:33 UTC, Naroh091 commented
Also waiting for this to get merged 🙏

2022-04-26 18:33 UTC, neSpecc requested changes

2022-04-26 18:33 UTC, neSpecc commented on src/components/modules/paste.ts
> +      const currentToolSanitizeConfig = BlockManager.currentBlock.tool.baseSanitizeConfig;
looks like the `sanitizeConfig` works wrong and we would better to fix it. Need to dig deeper.

2022-04-26 19:33 UTC, neSpecc commented
Looks like the PR is correct, but we have a problem with naming. See #2029

2022-04-26 19:34 UTC, gohabereg approved these changes

2022-04-26 19:35 UTC, neSpecc approved these changes

2022-04-26 19:42 UTC, merged