Vertical toolbox fixes
codex-team/editor.js pull request #2017
Opened 2022-04-09 13:53 UTC by TatianaFomina

Includes fixes on
- arrow keys navigation within toolbox search bar
- hidden popover causing rendering issues

2022-04-09 22:34 UTC, neSpecc requested changes

2022-04-09 22:34 UTC, neSpecc commented on src/components/flipper.ts
>      const isCurrentItemIsFocusedInput = this.iterator.currentItem == document.activeElement;
do we need this statement in the new logic? Looks like it was used to handle similar problem with arrows in inputs, but it does not cover the case when you allows up/down but disallow left/right.

2022-04-09 22:34 UTC, neSpecc commented on src/styles/popover.css
> -  visibility: hidden;
unfortunatelly, this breaks the animation. Try to open/close the popover several times.

2022-04-11 19:24 UTC, neSpecc approved these changes

2022-04-11 20:56 UTC, gohabereg approved these changes

2022-04-14 15:08 UTC, merged