fix(ui): toolbox items labels i18n
codex-team/editor.js pull request #2031
Opened 2022-04-27 15:12 UTC by TatianaFomina

Return the ability to display localized labels for toolbox items

2022-04-27 15:48 UTC, ilyamore88 approved these changes
👍

2022-04-27 15:54 UTC, gohabereg approved these changes

2022-04-27 15:54 UTC, gohabereg commented on docs/CHANGELOG.md
> +— `Fix` — Tool title is not translated anymore [#2030](https://github.com/codex-team/editor.js/issues/2030)
```suggestion

— `Fix` — Tool title is not translated anymore [#2030](https://github.com/codex-team/editor.js/issues/2030)
```

2022-04-27 16:18 UTC, neSpecc requested changes

2022-04-27 16:18 UTC, neSpecc commented on docs/CHANGELOG.md
> +— `Fix` — Tool title is not translated anymore [#2030](https://github.com/codex-team/editor.js/issues/2030)
```suggestion
— `Fix` — The I18n of Tools` titles at the Toolbox now works correctly [#2030](https://github.com/codex-team/editor.js/issues/2030)
```

2022-04-27 16:18 UTC, neSpecc commented on src/components/ui/toolbox.ts
> +          label: I18n.t(I18nInternalNS.toolNames, tool.toolbox.title),
what if user (or tool itself) does not specified the `toolbox.title`? The title is the optional field.

Please, test this case. Maybe there should be something like `tool.title || _.capitalize(tool.name)`

2022-04-27 16:58 UTC, neSpecc commented
what do you think about adding a tests for these cases?

2022-04-28 05:51 UTC, TatianaFomina commented
> what do you think about adding a tests for these cases?

Added a test

2022-04-28 08:06 UTC, neSpecc requested changes

2022-04-28 08:06 UTC, neSpecc commented on src/components/ui/toolbox.ts
> +          label: I18n.t(I18nInternalNS.toolNames, tool.toolbox.title || _.capitalize(tool.name)),
>_.capitalize(tool.name)

this statement is not covered by tests

2022-04-28 15:32 UTC, TatianaFomina commented on src/components/ui/toolbox.ts
> +          label: I18n.t(I18nInternalNS.toolNames, tool.toolbox.title || _.capitalize(tool.name)),
added a test case

2022-04-28 15:52 UTC, neSpecc approved these changes
Brilliant

2022-04-28 16:26 UTC, merged