fix(ui): Prevent scrolling top when opening toolbox on mobile
codex-team/editor.js pull request #2034
Opened 2022-04-29 05:07 UTC by TatianaFomina

- Fixes issue when page is scrolled top if you open toolbox on mobile
- Also contains small typo fix `'Noting'` -> `'Nothing'`

2022-04-29 05:18 UTC, neSpecc approved these changes
add a changelog please

2022-04-29 05:22 UTC, neSpecc requested changes

2022-04-29 05:22 UTC, neSpecc commented on src/styles/ui.css
> +  position: fixed;
I'm afraid that the reflow of the whole DOM will cost too much

2022-05-01 11:06 UTC, neSpecc approved these changes

2022-05-01 11:16 UTC, ilyamore88 commented on docs/CHANGELOG.md
> +### 2.24.1
Why are there two same versions?

2022-05-01 11:18 UTC, TatianaFomina commented on docs/CHANGELOG.md
> +### 2.24.1
fixed

2022-05-01 11:18 UTC, ilyamore88 approved these changes

2022-05-01 11:43 UTC, merged