Improved blocks.insert() by allowing passing parameters as an object …
codex-team/editor.js pull request #2095
Opened 2022-07-12 00:33 UTC by zang77

…(#7)

* Improved block.insert() by allowing passing parameters as an object

* Fixed some issues commented out from last pr. Set the default parameter for insert.

* Added changelog for insert function.

2022-07-12 07:00 UTC, aditink commented
Fixes issue #1817

2022-11-25 21:15 UTC, neSpecc requested changes

2022-11-25 21:15 UTC, neSpecc commented on src/components/modules/api/blocks.ts
>    public insert = (
it would be better to save the backward capability

2022-11-25 21:15 UTC, neSpecc commented on types/api/block.d.ts
> +export interface NewBlock {
```suggestion
export interface BlockInsertionParams {
```

2023-02-18 02:04 UTC, neSpecc commented
The solution should save the backward compatibility, but this PR is dropping it.

2023-02-18 02:04 UTC, closed without merging