Also check root node for mutationFree attribute
codex-team/editor.js pull request #2164
Opened 2022-11-10 09:48 UTC by oskarer

This allows to set `mutationFree` on any element added in the `render()` function, not just added or removed child nodes. For example this case which I encountered (not a full example, somewhat psuedo code);

```
render() {
  const container = document.createElement('div');
  // Also add some input field to set video URL here

  if (data.url) {
    const video = document.createElement('lite-youtube');
    video.dataset.mutationFree = 'true'; // Only works with this PR
    video.setAttribute('videoid', 'someID');
    container.appendChild(video);
  }

  return container;
}
```

This would trigger the `onChange` event since `lite-youtube` is a custom element that adds a lot of elements to the DOM after `render()` has run. But in reality nothing has really changed, the only thing that should trigger a change is change of the video URL in the `<input>` field.

2022-11-25 23:19 UTC, neSpecc requested changes

2022-11-25 23:19 UTC, neSpecc commented on src/components/block/index.ts
> +    });
This code should be separated into several parts with clear names. For now, it is hard to read and understand.

Also, we need to write a tests for the covered cases.

2023-02-17 18:25 UTC, neSpecc commented
It would be great to have a test case for that change.

I think we'll include it in the upcoming release.

2023-02-24 12:55 UTC, oskarer commented
> It would be great to have a test case for that change.
> 
> I think we'll include it in the upcoming release.

@neSpecc Thanks, can you give me any pointers where a great place would be to add a spec for it? At least I've rebased now so it's mergeable.

2023-03-20 17:19 UTC, neSpecc commented
> > It would be great to have a test case for that change.
> > I think we'll include it in the upcoming release.
> 
> @neSpecc Thanks, can you give me any pointers where a great place would be to add a spec for it? At least I've rebased now so it's mergeable.

I guess `/test/cypress/tests/onChange.spec.ts` will be a nice place

2025-11-18 07:52 UTC, closed without merging